package user;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import login.User_Login;

public class User_Dashboard extends javax.swing.JFrame {

    private static String username;
    /**
     * Creates new form User_Dashboard
     */
    Connection con;
    
    public User_Dashboard(String username)
    {
        initComponents();
        
        this.username = username;
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        this.setTitle("CITY TRAVELS");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        txt_welcome.setText("Welcome  "+username+"...");
        
        con = makeCon();
        setData();
        
        TableHeader();
    }
    
    public User_Dashboard() {
        initComponents();
    }
    
    private void TableHeader()
    {
        JTableHeader thead = tbl_buss.getTableHeader();
        thead.setBackground(Color.BLACK);
        thead.setFont(new Font("Times New Romains", Font.BOLD, 14));
        
        TableColumn col1 = tbl_buss.getColumnModel().getColumn(0);
        col1.setPreferredWidth(79);
        TableColumn col2 = tbl_buss.getColumnModel().getColumn(1);
        col2.setPreferredWidth(135);
        TableColumn col3 = tbl_buss.getColumnModel().getColumn(2);
        col3.setPreferredWidth(135);
        TableColumn col4 = tbl_buss.getColumnModel().getColumn(3);
        col4.setPreferredWidth(105);
        TableColumn col5 = tbl_buss.getColumnModel().getColumn(4);
        col5.setPreferredWidth(120);
        TableColumn col6 = tbl_buss.getColumnModel().getColumn(5);
        col6.setPreferredWidth(120);
        TableColumn col7 = tbl_buss.getColumnModel().getColumn(6);
        col7.setPreferredWidth(80);
        
    }
    
    private Connection makeCon(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/city_travels", "root", "mysql@123");
            return con;
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
            return null;
        }
    }
    
    private void setData(){
        try {
            String q = "select * from bus_schedule";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q);
            while(rs.next()){
                String b_no = rs.getString(1);
                String f = rs.getString(2);
                String t = rs.getString(3);
                String dt = rs.getString(4);
                String d_time = rs.getString(5);
                String seats = String.valueOf(rs.getInt(6));
                String price = String.valueOf(rs.getInt(7));
                
                String tbData[] = {b_no, f, t, dt, d_time, seats, price};
                DefaultTableModel tbm = (DefaultTableModel) tbl_buss.getModel();
                
                tbm.addRow(tbData);
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_welcome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_buss = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_booking = new javax.swing.JMenu();
        menu_calcellation = new javax.swing.JMenu();
        menu_mybookings = new javax.swing.JMenu();
        menu_hs = new javax.swing.JMenu();
        menu_about = new javax.swing.JMenu();
        menu_profile = new javax.swing.JMenu();
        user_logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/Schedule(48x48).png"))); // NOI18N
        jLabel1.setText("  Bus Schedule");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 875, 55));

        txt_welcome.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        txt_welcome.setForeground(new java.awt.Color(0, 0, 0));
        txt_welcome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txt_welcome.setText("Welcome  Error,");
        txt_welcome.setMaximumSize(new java.awt.Dimension(126, 25));
        txt_welcome.setMinimumSize(new java.awt.Dimension(126, 25));
        txt_welcome.setPreferredSize(new java.awt.Dimension(126, 25));
        getContentPane().add(txt_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 11, 400, -1));

        jPanel1.setBackground(new java.awt.Color(252, 237, 218));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_buss.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tbl_buss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus No.", "From", "To", "Date", "Departure Time", "Available Seats", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_buss.setRowHeight(25);
        tbl_buss.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_buss);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 776, 342));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("* You can resize table's column size according to your requirement ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 46, 876, 525));

        jPanel2.setBackground(new java.awt.Color(238, 78, 52));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 876, 45));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(429, 40));

        menu_booking.setText("Booking");
        menu_booking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu_booking.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menu_booking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_bookingMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_booking);

        menu_calcellation.setText("Cancellation");
        menu_calcellation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu_calcellation.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menu_calcellation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_calcellationMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_calcellation);

        menu_mybookings.setText("My Bookings");
        menu_mybookings.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu_mybookings.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menu_mybookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_mybookingsMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_mybookings);

        menu_hs.setText("Help & Support");
        menu_hs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu_hs.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menu_hs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_hsMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_hs);

        menu_about.setText("About Us");
        menu_about.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu_about.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menu_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_aboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_about);

        menu_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/Profile.png"))); // NOI18N
        menu_profile.setText("Profile");
        menu_profile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menu_profile.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menu_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_profileMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_profile);

        user_logout.setForeground(new java.awt.Color(255, 0, 0));
        user_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/logout.png"))); // NOI18N
        user_logout.setText(" Logout");
        user_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user_logout.setMargin(new java.awt.Insets(3, 10, 3, 10));
        user_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(user_logout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_bookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_bookingMouseClicked
        // TODO add your handling code here:
        dispose();
        Booking b = new Booking(username);
    }//GEN-LAST:event_menu_bookingMouseClicked

    private void menu_calcellationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_calcellationMouseClicked
        // TODO add your handling code here:
        dispose();
        Cancellation c = new Cancellation(username);
    }//GEN-LAST:event_menu_calcellationMouseClicked

    private void menu_mybookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mybookingsMouseClicked
        // TODO add your handling code here:
        dispose();
        My_Bookings mb = new My_Bookings(username);
    }//GEN-LAST:event_menu_mybookingsMouseClicked

    private void menu_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_aboutMouseClicked
        // TODO add your handling code here:
        
        dispose();
        About_frame af = new About_frame(username);
    }//GEN-LAST:event_menu_aboutMouseClicked

    private void user_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_logoutMouseClicked
        // TODO add your handling code here:

        int i = JOptionPane.showConfirmDialog(null, "Do you really want to logout?", "Message", JOptionPane.YES_NO_OPTION);
        
        if(i == 0)
        {
            dispose();
            User_Login ul = new User_Login();
        }
        
    }//GEN-LAST:event_user_logoutMouseClicked

    private void menu_hsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_hsMouseClicked
        // TODO add your handling code here:
        
        dispose();
        Help_Support hs = new Help_Support(username);
    }//GEN-LAST:event_menu_hsMouseClicked

    private void menu_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_profileMouseClicked
        // TODO add your handling code here:
        
        dispose();
        MyProfile mp = new MyProfile(username);
    }//GEN-LAST:event_menu_profileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_about;
    private javax.swing.JMenu menu_booking;
    private javax.swing.JMenu menu_calcellation;
    private javax.swing.JMenu menu_hs;
    private javax.swing.JMenu menu_mybookings;
    private javax.swing.JMenu menu_profile;
    private javax.swing.JTable tbl_buss;
    private javax.swing.JLabel txt_welcome;
    private javax.swing.JMenu user_logout;
    // End of variables declaration//GEN-END:variables
}
