package login;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Change_Password extends javax.swing.JFrame{

    private static String username;
    /**
     * Creates new form Admin_Login
     */
    Connection con;
    
    public Change_Password(){
        initComponents();
        /*setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        setTitle("CITY TRAVELS");
        setResizable(false);
        setLocationRelativeTo(null);
        
        setVisible(true);*/
    }
    
    public Change_Password(String username) {
        
        this.username = username;
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        setTitle("CITY TRAVELS");
        setResizable(false);
        setLocationRelativeTo(null);
        
        setVisible(true);
        
        try {
            con = makeCon();
        } catch (IOException ex) {
            Logger.getLogger(Change_Password.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Connection makeCon() throws IOException{
        Properties props = new Properties();
        InputStream input = getClass().getClassLoader().getResourceAsStream("resources/config.properties");
        if (input != null) {
            props.load(input);
        } else {
            throw new FileNotFoundException("Property file not found");
        }

        String url = props.getProperty("db.url");
        String username = props.getProperty("db.username");
        String password = props.getProperty("db.password");

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, username, password);
            return con;
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_createnewpwd = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        txt_confirmpwd = new javax.swing.JPasswordField();
        btn_reset = new javax.swing.JButton();
        btn_newpwd_back = new javax.swing.JButton();
        txt_newpwd = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_createnewpwd.setFont(new java.awt.Font("Baskerville Old Face", 1, 28)); // NOI18N
        lbl_createnewpwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_createnewpwd.setText("Create New Password");
        getContentPane().add(lbl_createnewpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 18, 480, -1));

        lbl_1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl_1.setText("New Password : ");
        getContentPane().add(lbl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 96, -1, -1));

        lbl_2.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl_2.setText("Confirm Password : ");
        getContentPane().add(lbl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 153, -1, -1));

        txt_confirmpwd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txt_confirmpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 150, 175, -1));

        btn_reset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 212, -1, -1));

        btn_newpwd_back.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_newpwd_back.setText("Back");
        btn_newpwd_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newpwd_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_newpwd_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 212, -1, -1));

        txt_newpwd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txt_newpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 93, 175, -1));

        jPanel1.setBackground(new java.awt.Color(238, 78, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 481, 64));

        jPanel2.setBackground(new java.awt.Color(252, 237, 218));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 480, 211));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        
        String newpwd = txt_newpwd.getText();
        String cfmpwd = txt_confirmpwd.getText();
        
        if(!newpwd.isEmpty() && !cfmpwd.isEmpty())
        {
            try
            {
                File ff = new File("C:\\City Bus\\Users Data\\User_"+username+"\\ud_pwd.txt");
                ff.delete();
                
                if(newpwd.equals(cfmpwd))
                {
                    try
                    {
                        ff = new File("C:\\City Bus\\Users Data\\User_"+username+"\\ud_pwd.txt");
                        FileWriter fw = new FileWriter(ff);
                    
                        ff.createNewFile();
                    
                        int i, ch;
                        for(i = 0; i<cfmpwd.length(); i++)
                        {
                            ch = cfmpwd.charAt(i);
                            ch += 5;
                            fw.write(ch);
                        }
                        fw.close();
                        
                        updatePwd(newpwd);
                    
                        dispose();
                        User_Login ulu = new User_Login();
                }
                catch(Exception e)
                {
                    System.out.print("\n NEW PASSWORD FILE CREATE ERROR : "+e);
                }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Please Check, Comfirm Password does not match!");
                }
                               
            } 
            catch (Exception ex)
            {
                System.out.print("\n ERROR 404 : "+ex);
            }
        }
        else if(newpwd.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill necessary detail of NEW PASSWORD...!!");
        }
        else if(cfmpwd.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill necessary detail of CONFIRM PASSWORD...!!");
        }
            
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_newpwd_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newpwd_backActionPerformed
        // TODO add your handling code here:
        
        dispose();
        Password_Verification pwdv = new Password_Verification();
    }//GEN-LAST:event_btn_newpwd_backActionPerformed

    private void updatePwd(String pwd){
        try {
            String q = "update user_details set password=? where username=?";
            PreparedStatement ps = con.prepareStatement(q);
            ps.setString(1, pwd);
            ps.setString(2, username);
            ps.executeUpdate();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Change_Password.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_newpwd_back;
    private javax.swing.JButton btn_reset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_createnewpwd;
    private javax.swing.JPasswordField txt_confirmpwd;
    private javax.swing.JPasswordField txt_newpwd;
    // End of variables declaration//GEN-END:variables
}
