package login;

import java.awt.Toolkit;

public class First_frame extends javax.swing.JFrame {

    /**
     * Creates new form First_frame
     */
    public First_frame() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        setTitle("CITY TRAVELS");
        setResizable(false);
        setLocationRelativeTo(null);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_hader = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_user = new javax.swing.JButton();
        btn_admin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_hader.setFont(new java.awt.Font("Baskerville Old Face", 1, 26)); // NOI18N
        lbl_hader.setText("City Bus Reservation System");
        getContentPane().add(lbl_hader, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 36, -1, -1));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Bus-Favicon.png"))); // NOI18N
        lbl_logo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 16, 62, 62));

        jPanel1.setBackground(new java.awt.Color(238, 78, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 100));

        jPanel2.setBackground(new java.awt.Color(252, 237, 218));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_user.setBackground(new java.awt.Color(102, 102, 255));
        btn_user.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        btn_user.setForeground(new java.awt.Color(0, 0, 0));
        btn_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/user(20x20).png"))); // NOI18N
        btn_user.setText(" User");
        btn_user.setBorderPainted(false);
        btn_user.setMargin(new java.awt.Insets(2, 10, 3, 14));
        btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userActionPerformed(evt);
            }
        });
        jPanel2.add(btn_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 100, 35));

        btn_admin.setBackground(new java.awt.Color(102, 102, 255));
        btn_admin.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        btn_admin.setForeground(new java.awt.Color(0, 0, 0));
        btn_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Admin_(20x20).png"))); // NOI18N
        btn_admin.setText(" Admin");
        btn_admin.setBorderPainted(false);
        btn_admin.setMargin(new java.awt.Insets(2, 10, 3, 14));
        btn_admin.setMaximumSize(new java.awt.Dimension(87, 28));
        btn_admin.setMinimumSize(new java.awt.Dimension(87, 28));
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        jPanel2.add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 170, -1, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/bus-13947.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 99, 650, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        // TODO add your handling code here:
        
        dispose();
        Admin_Login al = new Admin_Login();
    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userActionPerformed
        // TODO add your handling code here:
        
        dispose();
        User_Login ul = new User_Login();
        //ul.setVisible(true);
    }//GEN-LAST:event_btn_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin;
    private javax.swing.JButton btn_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_hader;
    private javax.swing.JLabel lbl_logo;
    // End of variables declaration//GEN-END:variables
}
