package login;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;

public class Password_Verification extends javax.swing.JFrame {

    /**
     * Creates new form Password_Verification
     */
    public Password_Verification() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        setTitle("CITY TRAVELS");
        setResizable(false);
        setLocationRelativeTo(null);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_varification = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_2 = new javax.swing.JLabel();
        txt_luckyno = new javax.swing.JTextField();
        btn_verify = new javax.swing.JButton();
        btn_pwdvari_back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_varification.setFont(new java.awt.Font("Baskerville Old Face", 1, 28)); // NOI18N
        lbl_varification.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_varification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/Var_id(46x46).png"))); // NOI18N
        lbl_varification.setText("  Verification");
        getContentPane().add(lbl_varification, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 444, 54));

        lbl_1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl_1.setText("Username : ");
        getContentPane().add(lbl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 104, -1, -1));

        txt_username.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 102, 158, -1));

        lbl_2.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl_2.setText(" Lucky Number : ");
        getContentPane().add(lbl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 171, -1, -1));

        txt_luckyno.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_luckyno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_luckynoActionPerformed(evt);
            }
        });
        txt_luckyno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_luckynoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_luckyno, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 169, 158, -1));

        btn_verify.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_verify.setText("Verify");
        btn_verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verifyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 236, -1, -1));

        btn_pwdvari_back.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_pwdvari_back.setText("Back");
        btn_pwdvari_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pwdvari_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pwdvari_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 236, -1, -1));

        jPanel1.setBackground(new java.awt.Color(238, 78, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 445, 73));

        jPanel2.setBackground(new java.awt.Color(252, 237, 218));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 446, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verifyActionPerformed
        // TODO add your handling code here:
        
        String un = txt_username.getText();
        String ln = txt_luckyno.getText();
        
        if(!un.isEmpty() && !ln.isEmpty())
        {
            try
            {
                FileReader fr = new FileReader("c:\\City Bus\\Users Data\\User_"+un+"\\ud_"+un+".txt");
                BufferedReader br = new BufferedReader(fr);
            
                String un_pv = "";
                un_pv = br.readLine();
                fr.close();
                
                try
                {
                    fr = new FileReader("c:\\City Bus\\Users Data\\User_"+un+"\\ud_luckyno.txt");
                    br = new BufferedReader(fr);
                
                    String luckyno_data = "", str = "";
                    char ch;
                    int i = 0;
                    while(i != -1)
                    {
                        i = br.read();
                    
                        if(i != -1)
                        {
                            i -= 70;
                            ch = (char)(i);
                            str = String.valueOf(ch);
                            luckyno_data = luckyno_data + str;
                            i = 0;
                        }
                    }
                    fr.close();  
                    
                    if(luckyno_data.equals(ln))
                    {
                        dispose();
                        Change_Password cp = new Change_Password(un);       
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Invalid Credentials/Lucky Number...!!");
                    }
                }
                catch(Exception e)
                {
                    System.out.print("\n ERROR : "+e+"\n LUCKY NO FILE NOT FOUND!!");
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Invalid Credentials/User...!!");
            }
        }
        else if(un.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill necessary detail of USERNAME...!!");
        }
        else if(ln.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill necessary detail of LUCKY NUMBER...!!");
        }
    }//GEN-LAST:event_btn_verifyActionPerformed

    private void btn_pwdvari_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pwdvari_backActionPerformed
        // TODO add your handling code here:
        
        dispose();
        User_Login ulo = new User_Login();
    }//GEN-LAST:event_btn_pwdvari_backActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_luckynoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_luckynoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_luckynoActionPerformed

    private void txt_luckynoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_luckynoKeyTyped
        // TODO add your handling code here:
        
        char ln = evt.getKeyChar();
        
        if(!Character.isDigit(ln))
            evt.consume();
    }//GEN-LAST:event_txt_luckynoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password_Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password_Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password_Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password_Verification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password_Verification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pwdvari_back;
    private javax.swing.JButton btn_verify;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_varification;
    private javax.swing.JTextField txt_luckyno;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
