package login;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class User_SignUp extends javax.swing.JFrame {

    /**
     * Creates new form User_SignUp
     */
    public User_SignUp() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        setTitle("CITY TRAVELS");
        setResizable(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    
    private Connection makeCon() throws IOException{
        Properties props = new Properties();
        InputStream input = getClass().getClassLoader().getResourceAsStream("resources/config.properties");
        if (input != null) {
            props.load(input);
        } else {
            throw new FileNotFoundException("Property file not found");
        }

        String url = props.getProperty("db.url");
        String username = props.getProperty("db.username");
        String password = props.getProperty("db.password");
//        Connection conn = DriverManager.getConnection(url, username, password);

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, username, password);
            return con;
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
            return null;
        }
    }
    
    private void setData(Connection con, String un, String fn, String ln, String em, String pwd, String lckn){
        try {
            String q = "insert into user_details(username,first_name,last_name,email_id,password,lucky_number) values(?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(q);
            ps.setString(1, un);
            ps.setString(2, fn);
            ps.setString(3, ln);
            ps.setString(4, em);
            ps.setString(5, pwd);
            ps.setInt(6, Integer.parseInt(lckn));
            ps.executeUpdate();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(User_SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_h_signupform = new javax.swing.JLabel();
        lbl1_1 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        lbl_2 = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        lbl_3 = new javax.swing.JLabel();
        txt_signup_username = new javax.swing.JTextField();
        lbl_4 = new javax.swing.JLabel();
        lbl_5 = new javax.swing.JLabel();
        txt_signup_confirmpwd = new javax.swing.JPasswordField();
        txt_signup_pwd = new javax.swing.JPasswordField();
        lbl_6 = new javax.swing.JLabel();
        txt_signup_luckyno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbl_7 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        btn_signup = new javax.swing.JButton();
        btn_signup_back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_h_signupform.setFont(new java.awt.Font("Baskerville Old Face", 1, 28)); // NOI18N
        lbl_h_signupform.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_h_signupform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/signup.png"))); // NOI18N
        lbl_h_signupform.setText("  Sign-Up Form");
        getContentPane().add(lbl_h_signupform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 650, 59));

        lbl1_1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl1_1.setText("First Name* : ");
        getContentPane().add(lbl1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 111, -1, -1));

        txt_firstname.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_firstnameKeyTyped(evt);
            }
        });
        getContentPane().add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 108, 140, -1));

        lbl_2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_2.setText("Last Name* : ");
        getContentPane().add(lbl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 111, -1, -1));

        txt_lastname.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });
        txt_lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_lastnameKeyTyped(evt);
            }
        });
        getContentPane().add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 108, 140, -1));

        lbl_3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_3.setText("Username* : ");
        getContentPane().add(lbl_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 170, -1, -1));

        txt_signup_username.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(txt_signup_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 167, 140, -1));

        lbl_4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_4.setText("Password* : ");
        getContentPane().add(lbl_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 170, -1, -1));

        lbl_5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_5.setText("Confirm Password* : ");
        getContentPane().add(lbl_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 230, -1, -1));

        txt_signup_confirmpwd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(txt_signup_confirmpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 227, 139, -1));

        txt_signup_pwd.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(txt_signup_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 167, 139, -1));

        lbl_6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbl_6.setText("Lucky Number* : ");
        getContentPane().add(lbl_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 292, -1, -1));

        txt_signup_luckyno.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txt_signup_luckyno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_signup_luckynoMouseEntered(evt);
            }
        });
        txt_signup_luckyno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_signup_luckynoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_signup_luckyno, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 289, 140, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 50));
        jLabel8.setText("*This is security question.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 294, -1, -1));

        lbl_7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbl_7.setText("E-mail ID* : ");
        getContentPane().add(lbl_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 352, -1, -1));

        txt_email.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 349, 262, -1));

        btn_signup.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_signup.setText("Sign Up");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 423, -1, -1));

        btn_signup_back.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_signup_back.setText("Back");
        btn_signup_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signup_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 423, -1, -1));

        jPanel1.setBackground(new java.awt.Color(238, 78, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 70));

        jPanel2.setBackground(new java.awt.Color(252, 237, 218));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 650, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
        
        String username, pwd, cfm_pwd, fname, lname, luckyno, email;
        
        username = txt_signup_username.getText().trim();
        fname = txt_firstname.getText().trim();
        lname = txt_lastname.getText().trim();
        pwd = txt_signup_pwd.getText();
        cfm_pwd = txt_signup_confirmpwd.getText();
        email = txt_email.getText().trim();
        luckyno = txt_signup_luckyno.getText();
        
        if(!username.isEmpty() && !pwd.isEmpty() && !fname.isEmpty() && !lname.isEmpty() && !luckyno.isEmpty() && !email.isEmpty())
        {       
            if(pwd.equals(cfm_pwd))
            {  
                String sub = "@gmail.com";
                String sub2 = "@yahoo.com";
                if(email.contains(sub) || email.contains(sub2))
                {
                    try
                    {
                        File f = new File("C:\\City Bus\\Users Data\\User_"+username);
                        try
                        {
                            if(!f.exists())
                            {
                                f.mkdirs();
                            }
                        }
                        catch(Exception e)
                        {
                            System.out.print("\n CREATE FOLDER ERROR : "+e.getMessage()); 
                        }

                        String path = "C:\\City Bus\\Users Data\\User_"+username;
                        File ft = new File(path+"\\ud_"+username+".txt");
                        if(!ft.exists())
                        {	
                        
                            ft.createNewFile();
			
                            try
                            {
                                FileWriter fw = new FileWriter(path+"\\ud_"+username+".txt");
                                fw.write(username+"\n"+fname+"\n"+lname+"\n"+email);
                                fw.close();

                                try 
                                {
                                    FileOutputStream fos = new FileOutputStream(path+"\\ud_pwd.txt");
			
                                    int i, ch;
                                    for(i = 0; i<cfm_pwd.length(); i++)
                                    {
                                        ch = cfm_pwd.charAt(i);
                                        
                                        ch += 5;
                                        fos.write(ch);
                                    }
                                    fos.close();
                                
                                    fos = new FileOutputStream(path+"\\ud_luckyno.txt");                                
                               
                                    for(i = 0; i<luckyno.length(); i++)
                                    {
                                        ch = luckyno.charAt(i);
                                    
                                        ch += 70;
                                        fos.write(ch);
                                    }
                                    fos.close(); 
                                
                                }
                                catch(Exception e)
                                {
                                    System.out.print("\n ERROR 404 : "+e);
                                }
                                Connection con = makeCon();
                                setData(con, username, fname, lname, email, pwd, luckyno);
                                dispose();
                                User_Login usl = new User_Login();
                                //System.out.print("\n File Created Successfully..!!");
                            }
                            catch(Exception e)
                            {
                                System.out.print("\n FILE WRITE ERROR : "+e.getMessage());
                            }
                     
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"Username Already Exists In Your System...\nPlease try with other USERNAME.");
                        }
                    }
                    catch(Exception e)
                    {
                        System.out.print("\n ERROR 404 : "+e.getMessage());	
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Please, Enter valid format of email-ID...!!");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please Check, Comfirm Password does not match!");
            }
        }
        else if(fname.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill necessary detail of FIRST NAME...!!");
        }
        else if(lname.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill necessary detail of LAST NAME...!!");
        }
        else if(username.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill necessary detail of USERNAME...!!");
        }
        else if(pwd.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill necessary detail of PASSWORD...!!");
        }
        else if(luckyno.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill necessary detail of LUCKY NUMBER...!!");
        }
        else if(email.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill necessary detail of E-mail...!!");
        }
        
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btn_signup_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signup_backActionPerformed
        // TODO add your handling code here:
        
        dispose();
        User_Login usl = new User_Login();
    }//GEN-LAST:event_btn_signup_backActionPerformed

    private void txt_signup_luckynoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_signup_luckynoKeyTyped
        // TODO add your handling code here:
        
        char ln = evt.getKeyChar();
        
        if(!Character.isDigit(ln))
            evt.consume();
    }//GEN-LAST:event_txt_signup_luckynoKeyTyped

    private void txt_signup_luckynoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_signup_luckynoMouseEntered
        // TODO add your handling code here:
        
        txt_signup_luckyno.setToolTipText("Fill this carefully!! This will help you to change your password.");
    }//GEN-LAST:event_txt_signup_luckynoMouseEntered

    private void txt_firstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstnameKeyTyped
        // TODO add your handling code here:
        
        char fname = evt.getKeyChar();
        
        if(Character.isDigit(fname))
            evt.consume();
    }//GEN-LAST:event_txt_firstnameKeyTyped

    private void txt_lastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastnameKeyTyped
        // TODO add your handling code here:
        
        char lname = evt.getKeyChar();
        
        if(Character.isDigit(lname))
            evt.consume();
    }//GEN-LAST:event_txt_lastnameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signup;
    private javax.swing.JButton btn_signup_back;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_5;
    private javax.swing.JLabel lbl_6;
    private javax.swing.JLabel lbl_7;
    private javax.swing.JLabel lbl_h_signupform;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JPasswordField txt_signup_confirmpwd;
    private javax.swing.JTextField txt_signup_luckyno;
    private javax.swing.JPasswordField txt_signup_pwd;
    private javax.swing.JTextField txt_signup_username;
    // End of variables declaration//GEN-END:variables
}
