package login;

import user.User_Dashboard;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class User_Login extends JFrame {

    /**
     * Creates new form User_login
     */
    public User_Login() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        setTitle("CITY TRAVELS");
        setResizable(false);
        setLocationRelativeTo(null);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_userLogin = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        btn_ulogin = new javax.swing.JButton();
        btn_forgot = new javax.swing.JButton();
        txt_pwd = new javax.swing.JPasswordField();
        lbl_1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btn_signup = new javax.swing.JButton();
        lbl_2 = new javax.swing.JLabel();
        btn_userlogin_back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusCycleRoot(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_userLogin.setFont(new java.awt.Font("Baskerville Old Face", 1, 28)); // NOI18N
        lbl_userLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_userLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/login(48x48).png"))); // NOI18N
        lbl_userLogin.setText("  User Login");
        getContentPane().add(lbl_userLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 475, 58));

        lbl_username.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl_username.setText("Username  : ");
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 113, -1, -1));

        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 108, 172, -1));

        lbl_password.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        lbl_password.setText("Password  : ");
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 173, -1, -1));

        btn_ulogin.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_ulogin.setText("Login");
        btn_ulogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uloginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ulogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 238, -1, -1));

        btn_forgot.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_forgot.setText("Forgot");
        btn_forgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_forgotActionPerformed(evt);
            }
        });
        getContentPane().add(btn_forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 298, -1, -1));

        txt_pwd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        getContentPane().add(txt_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 168, 172, -1));

        lbl_1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(255, 0, 51));
        lbl_1.setText("Forgot Password?");
        getContentPane().add(lbl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 302, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 342, 475, 10));

        btn_signup.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_signup.setText("Sign Up");
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 370, -1, -1));

        lbl_2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbl_2.setForeground(new java.awt.Color(255, 0, 51));
        lbl_2.setText("Don't have account? New User?");
        getContentPane().add(lbl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 374, -1, -1));

        btn_userlogin_back.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btn_userlogin_back.setText("Back");
        btn_userlogin_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userlogin_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_userlogin_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 238, -1, -1));

        jPanel1.setBackground(new java.awt.Color(238, 78, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 476, 78));

        jPanel2.setBackground(new java.awt.Color(252, 237, 218));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 476, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_forgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_forgotActionPerformed
        // TODO add your handling code here:
        
        dispose();
        Password_Verification pv = new Password_Verification();
    }//GEN-LAST:event_btn_forgotActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
        
        dispose();
        User_SignUp us = new User_SignUp();
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btn_userlogin_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userlogin_backActionPerformed
        // TODO add your handling code here:
        
        dispose();
        First_frame ff1 = new First_frame();
    }//GEN-LAST:event_btn_userlogin_backActionPerformed

    private void btn_uloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uloginActionPerformed
        // TODO add your handling code here:
        
        String uname, pwd;
        
        uname = txt_username.getText();
        pwd = txt_pwd.getText();
        
        if(!uname.isEmpty() && !pwd.isEmpty()) {
        try
        {
            System.out.printf("\n Entered PWD = "+pwd);
            FileReader fr = new FileReader("c:\\City Bus\\Users Data\\User_"+uname+"\\ud_"+uname+".txt");
            BufferedReader br = new BufferedReader(fr);
            
            String un = "";
            un = br.readLine();
            fr.close();
            
            try
            {
                fr = new FileReader("c:\\City Bus\\Users Data\\User_"+uname+"\\ud_pwd.txt");
                br = new BufferedReader(fr);
                
                String pwd_data = "", str = "";
                char ch;
                int i = 0;
                while(i != -1)
                {
                    i = br.read();
                    
                    if(i != -1)
                    {
                        i -= 5;
                        ch = (char)(i);
                        str = String.valueOf(ch);
                        pwd_data = pwd_data + str;
                        i = 0;
                    }
                }
                fr.close();
                System.out.print("\n FILE PWD : "+pwd_data);
                    
                if(pwd_data.equals(pwd))
                {
                    dispose();
                    User_Dashboard ud = new User_Dashboard(uname);   
                }
                else
                { 
                    JOptionPane.showMessageDialog(null, "Invalid Credentials/User...!!"); 
                }
               
            }
            catch(Exception e)
            {
                System.out.print("\n ERROR 404 : PASSWORD FILE NOT FOUND!!");
            }
                      
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Invalid Credentials/User...!!");
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please fill necessary details...!!");
        }
                
    }//GEN-LAST:event_btn_uloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_forgot;
    private javax.swing.JButton btn_signup;
    private javax.swing.JButton btn_ulogin;
    private javax.swing.JButton btn_userlogin_back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_userLogin;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txt_pwd;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
