package admin;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Add_Bus extends javax.swing.JFrame {

    /**
     * Creates new form Add_Bus
     */
    public Add_Bus() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        this.setTitle("CITY TRAVELS");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    private Connection makeCon(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/city_travels", "root", "mysql@123");
            return con;
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
            return null;
        }
    }
    
    private void getData(Connection con){
        try {
            try (con) {
                String q = "insert into bus_schedule(bus_no,f,t,dt,departure_time,available_seats,price) values(?,?,?,?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(q);
                String date = add_date.getSelectedItem().toString();
                String month = add_month.getSelectedItem().toString();
                String year = add_year.getSelectedItem().toString();
                ps.setString(1, txt_add_busno.getText());
                ps.setString(2, txt_add_from.getText());
                ps.setString(3, txt_add_to.getText());
                ps.setString(4, date + "/" + month + "/" + year);
                ps.setString(5, txt_add_time.getText());
                ps.setInt(6, Integer.parseInt(txt_add_seats.getText()));
                ps.setInt(7, Integer.parseInt(txt_add_price.getText()));
                ps.executeUpdate();
                con.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Add_Bus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_add_from = new javax.swing.JTextField();
        txt_add_to = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_add_time = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_add_busno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_add_seats = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_add_price = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        add_back = new javax.swing.JButton();
        add_date = new javax.swing.JComboBox<>();
        add_month = new javax.swing.JComboBox<>();
        add_year = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/add_bus_Img.png"))); // NOI18N
        jLabel1.setText(" Add Bus");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 835, 54));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("From :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 141, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText(" To :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 141, 37, -1));

        txt_add_from.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_add_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_add_fromActionPerformed(evt);
            }
        });
        getContentPane().add(txt_add_from, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 138, 229, -1));

        txt_add_to.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txt_add_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 138, 224, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Date :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 238, 50, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Departurn Time  :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 238, -1, -1));

        txt_add_time.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txt_add_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 235, 135, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Bus No. :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 342, -1, -1));

        txt_add_busno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txt_add_busno, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 339, 101, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 339, 37, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("No. of seats :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 342, -1, -1));

        txt_add_seats.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_add_seats.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_seatsKeyTyped(evt);
            }
        });
        getContentPane().add(txt_add_seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 339, 100, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Price :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 342, -1, -1));

        txt_add_price.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_add_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_add_priceKeyTyped(evt);
            }
        });
        getContentPane().add(txt_add_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 339, 100, -1));

        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 420, 106, -1));

        add_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_back.setText("Back");
        add_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_backActionPerformed(evt);
            }
        });
        getContentPane().add(add_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 420, 101, -1));

        add_date.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add_date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_dateActionPerformed(evt);
            }
        });
        getContentPane().add(add_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 235, 60, -1));

        add_month.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        getContentPane().add(add_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 235, -1, -1));

        add_year.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025" }));
        getContentPane().add(add_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 235, -1, -1));

        jPanel1.setBackground(new java.awt.Color(238, 78, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 837, 91));

        jPanel2.setBackground(new java.awt.Color(252, 237, 218));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 837, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 837, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_dateActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if("".equals(txt_add_from.getText()) || "".equals(txt_add_to.getText()) || "".equals(txt_add_time.getText()) || "".equals(txt_add_busno.getText()) || "".equals(txt_add_seats.getText()) || "".equals(txt_add_price.getText())){
            JOptionPane.showMessageDialog(null, "Please Enter require field!");
        }
        else{
            Connection con = makeCon();
            getData(con);
            JOptionPane.showMessageDialog(null, "Bus is Added!");
            dispose();
            Admin_Dashboard ad = new Admin_Dashboard();
        }
                
    }//GEN-LAST:event_btn_addActionPerformed

    private void add_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_backActionPerformed
        // TODO add your handling code here:
        dispose();
        Admin_Dashboard ad = new Admin_Dashboard();
    }//GEN-LAST:event_add_backActionPerformed

    private void txt_add_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_add_fromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_add_fromActionPerformed

    private void txt_add_seatsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_seatsKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar))){
            evt.consume();
        }
    }//GEN-LAST:event_txt_add_seatsKeyTyped

    private void txt_add_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_add_priceKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if(!(Character.isDigit(TestChar))){
            evt.consume();
        }
    }//GEN-LAST:event_txt_add_priceKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Bus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_back;
    private javax.swing.JComboBox<String> add_date;
    private javax.swing.JComboBox<String> add_month;
    private javax.swing.JComboBox<String> add_year;
    private javax.swing.JButton btn_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_add_busno;
    private javax.swing.JTextField txt_add_from;
    private javax.swing.JTextField txt_add_price;
    private javax.swing.JTextField txt_add_seats;
    private javax.swing.JTextField txt_add_time;
    private javax.swing.JTextField txt_add_to;
    // End of variables declaration//GEN-END:variables
}
