package admin;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import login.First_frame;

public class Admin_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Dashboard
     */
    public Admin_Dashboard() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        this.setTitle("CITY TRAVELS");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        TableHeader();
        
        Connection con;
        try {
            con = makeCon();
            setData(con);
            calculateBus(con);
        } catch (IOException ex) {
            Logger.getLogger(Admin_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Connection makeCon() throws IOException{
        Properties props = new Properties();
        InputStream input = getClass().getClassLoader().getResourceAsStream("resources/config.properties");
        if (input != null) {
            props.load(input);
        } else {
            throw new FileNotFoundException("Property file not found");
        }

        String url = props.getProperty("db.url");
        String username = props.getProperty("db.username");
        String password = props.getProperty("db.password");

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, username, password);
            return con;
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
            return null;
        }
    }
    
    private void setData(Connection con){
        try {
            String q = "select * from bus_schedule";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q);
            while(rs.next()){
                String b_no = rs.getString(1);
                String f = rs.getString(2);
                String t = rs.getString(3);
                String dt = rs.getString(4);
                String d_time = rs.getString(5);
                String seats = String.valueOf(rs.getInt(6));
                String price = String.valueOf(rs.getInt(7));
                
                String tbData[] = {b_no, f, t, dt, d_time, seats, price};
                DefaultTableModel tbm = (DefaultTableModel) tbl_btt.getModel();
                
                tbm.addRow(tbData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void calculateBus(Connection con){
        try {
            String q = "select count(*) from bus_schedule";
            PreparedStatement ps = con.prepareStatement(q);
            ResultSet rs = ps.executeQuery(q);
            while(rs.next()){
                int cnt = rs.getInt(1);
                txt_totalbuses.setText(String.valueOf(cnt));
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Admin_Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void TableHeader()
    {
        JTableHeader thead = tbl_btt.getTableHeader();
        thead.setBackground(Color.BLACK);
        thead.setFont(new Font("Times New Roman", Font.BOLD, 16));
        
        TableColumn col1 = tbl_btt.getColumnModel().getColumn(0);
        col1.setPreferredWidth(79);
        TableColumn col2 = tbl_btt.getColumnModel().getColumn(1);
        col2.setPreferredWidth(135);
        TableColumn col3 = tbl_btt.getColumnModel().getColumn(2);
        col3.setPreferredWidth(135);
        TableColumn col4 = tbl_btt.getColumnModel().getColumn(3);
        col4.setPreferredWidth(105);
        TableColumn col5 = tbl_btt.getColumnModel().getColumn(4);
        col5.setPreferredWidth(120);
        TableColumn col6 = tbl_btt.getColumnModel().getColumn(5);
        col6.setPreferredWidth(120);
        TableColumn col7 = tbl_btt.getColumnModel().getColumn(6);
        col7.setPreferredWidth(80);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_btt = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_totalbuses = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menu_bookings = new javax.swing.JMenu();
        menu_managebus = new javax.swing.JMenu();
        mitem_addbus = new javax.swing.JMenuItem();
        mitem_edbus = new javax.swing.JMenuItem();
        menu_userdetails = new javax.swing.JMenu();
        admin_logout = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/Schedule(48x48).png"))); // NOI18N
        jLabel1.setText("  Bus Time Table");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 943, 54));

        tbl_btt.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tbl_btt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus No.", "From", "To", "Date", "Departure Time", "Available Seats", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_btt.setRowHeight(25);
        tbl_btt.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_btt);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 162, 846, 284));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("* Total No. of Buses :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 119, -1, -1));

        txt_totalbuses.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_totalbuses.setForeground(new java.awt.Color(255, 0, 0));
        txt_totalbuses.setText("0");
        getContentPane().add(txt_totalbuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 119, 37, -1));

        jPanel1.setBackground(new java.awt.Color(238, 78, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(252, 237, 218));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jMenuBar2.setPreferredSize(new java.awt.Dimension(249, 40));

        menu_bookings.setText("User Bookings");
        menu_bookings.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menu_bookings.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menu_bookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_bookingsMouseClicked(evt);
            }
        });
        jMenuBar2.add(menu_bookings);

        menu_managebus.setText("Manage Bus");
        menu_managebus.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menu_managebus.setMargin(new java.awt.Insets(3, 10, 3, 10));

        mitem_addbus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mitem_addbus.setText("Add Bus");
        mitem_addbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_addbusActionPerformed(evt);
            }
        });
        menu_managebus.add(mitem_addbus);

        mitem_edbus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mitem_edbus.setText("Edit/Delete Bus");
        mitem_edbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitem_edbusActionPerformed(evt);
            }
        });
        menu_managebus.add(mitem_edbus);

        jMenuBar2.add(menu_managebus);

        menu_userdetails.setText("User Details");
        menu_userdetails.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menu_userdetails.setMargin(new java.awt.Insets(3, 10, 3, 10));
        menu_userdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_userdetailsMouseClicked(evt);
            }
        });
        jMenuBar2.add(menu_userdetails);

        admin_logout.setForeground(new java.awt.Color(255, 0, 0));
        admin_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/logout.png"))); // NOI18N
        admin_logout.setText(" Logout");
        admin_logout.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        admin_logout.setMargin(new java.awt.Insets(3, 10, 3, 10));
        admin_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_logoutMouseClicked(evt);
            }
        });
        jMenuBar2.add(admin_logout);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitem_addbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_addbusActionPerformed
        // TODO add your handling code here:
        dispose();
        Add_Bus ab = new Add_Bus();
    }//GEN-LAST:event_mitem_addbusActionPerformed

    private void menu_bookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_bookingsMouseClicked
        // TODO add your handling code here:
        
        dispose();
        User_Bookings ub = new User_Bookings();
    }//GEN-LAST:event_menu_bookingsMouseClicked

    private void mitem_edbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitem_edbusActionPerformed
        // TODO add your handling code here:
        dispose();
        EDelete_Bus edb = new EDelete_Bus();
    }//GEN-LAST:event_mitem_edbusActionPerformed

    private void menu_userdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_userdetailsMouseClicked
        // TODO add your handling code here:
        dispose();
        User_Details ud = new User_Details();
    }//GEN-LAST:event_menu_userdetailsMouseClicked

    private void admin_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_logoutMouseClicked
        // TODO add your handling code here:
        
        int ans = JOptionPane.showConfirmDialog(null, "Do you really want to logout?", "Message", JOptionPane.YES_NO_OPTION);
        if(ans == 0)
        {
            dispose();
            First_frame ff = new First_frame();
        }
    }//GEN-LAST:event_admin_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu admin_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_bookings;
    private javax.swing.JMenu menu_managebus;
    private javax.swing.JMenu menu_userdetails;
    private javax.swing.JMenuItem mitem_addbus;
    private javax.swing.JMenuItem mitem_edbus;
    private javax.swing.JTable tbl_btt;
    private javax.swing.JLabel txt_totalbuses;
    // End of variables declaration//GEN-END:variables
}
