package admin;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

public class Search_User extends javax.swing.JFrame {

    /**
     * Creates new form Search_User
     */
    public Search_User() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        this.setTitle("CITY TRAVELS");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        TableHeader();
    }
    
    private void TableHeader()
    {
        JTableHeader thead = tbl_user.getTableHeader();
        thead.setBackground(Color.BLACK);
        thead.setFont(new Font("Times New Roman", Font.BOLD, 16));
        
        TableColumn col1 = tbl_user.getColumnModel().getColumn(0);
        col1.setPreferredWidth(130);
        TableColumn col2 = tbl_user.getColumnModel().getColumn(1);
        col2.setPreferredWidth(130);
        TableColumn col3 = tbl_user.getColumnModel().getColumn(2);
        col3.setPreferredWidth(130);
        TableColumn col4 = tbl_user.getColumnModel().getColumn(3);
        col4.setPreferredWidth(250);
        
    }
    
    private Connection makeCon(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/city_travels", "root", "mysql@123");
            return con;
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
            return null;
        }
    }
    
    private int checkCount(Connection con, String un){
        try {
            String q = "select count(*) from user_details where username = ?";
            PreparedStatement ps = con.prepareStatement(q);
            ps.setString(1, un);
            ResultSet rs = ps.executeQuery();
            int cnt = 0;
            while(rs.next()){
                cnt = rs.getInt(1);
            }
            return cnt;
        } catch (SQLException ex) {
            Logger.getLogger(Search_User.class.getName()).log(Level.SEVERE, null, ex);
            return 0;
        }
    }
    
    private void search(Connection con, String un){
        try {
            int cnt = checkCount(con,un);
            if(cnt == 0){
                JOptionPane.showMessageDialog(null, "No user found having username : " + un);
            }
            else{
                String q = "select username,first_name,last_name,email_id from user_details where username=?";
                PreparedStatement ps = con.prepareStatement(q);
                ps.setString(1, un);
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    String unn = rs.getString(1);
                    String fn = rs.getString(2);
                    String ln = rs.getString(3);
                    String em = rs.getString(4);
                    String[] cln = {"Username", "First Name", "Last Name", "E-Mail Id"};
                    tbl_user.setModel(new DefaultTableModel(cln, 0));
                    TableHeader();
                    DefaultTableModel dtbl = (DefaultTableModel)tbl_user.getModel();
                    String[] tData = {unn,fn,ln,em};
                    dtbl.addRow(tData);
                }
                con.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Search_User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_suser_username = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_user = new javax.swing.JTable();
        searchuser_back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/search_Img.png"))); // NOI18N
        jLabel1.setText(" Search User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 18, 939, 54));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Username :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 138, -1, -1));

        txt_suser_username.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(txt_suser_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 135, 244, -1));

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 137, 90, -1));

        tbl_user.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tbl_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "First Name", "Last Name", "E-Mail Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_user.setRowHeight(30);
        jScrollPane1.setViewportView(tbl_user);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 214, 859, 210));

        searchuser_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchuser_back.setText("Back");
        searchuser_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchuser_backActionPerformed(evt);
            }
        });
        getContentPane().add(searchuser_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 452, 100, -1));

        jPanel1.setBackground(new java.awt.Color(238, 78, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 941, 100));

        jPanel2.setBackground(new java.awt.Color(252, 237, 218));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 941, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchuser_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchuser_backActionPerformed
        // TODO add your handling code here:
        dispose();
        User_Details ud = new User_Details();
    }//GEN-LAST:event_searchuser_backActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String un = txt_suser_username.getText();
        if(un.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter username!!!");
        }
        else{
            Connection con = makeCon();
            search(con, un);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchuser_back;
    private javax.swing.JTable tbl_user;
    private javax.swing.JTextField txt_suser_username;
    // End of variables declaration//GEN-END:variables
}
