package admin;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

public class User_Details extends javax.swing.JFrame {

    /**
     * Creates new form User_Details
     */
    public User_Details() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Bus-Favicon.png")));
        this.setTitle("CITY TRAVELS");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        TableHeader();
        
        try {
            Connection con = makeCon();
            setData(con);
            calculateUser(con);
        } catch (IOException ex) {
            Logger.getLogger(User_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Connection makeCon() throws IOException{
        Properties props = new Properties();
        InputStream input = getClass().getClassLoader().getResourceAsStream("resources/config.properties");
        if (input != null) {
            props.load(input);
        } else {
            throw new FileNotFoundException("Property file not found");
        }

        String url = props.getProperty("db.url");
        String username = props.getProperty("db.username");
        String password = props.getProperty("db.password");

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, username, password);
            return con;
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
            return null;
        }
    }
    
    private void setData(Connection con){
        try {
            String q = "select username,first_name,last_name,email_id from user_details";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(q);
            while(rs.next()){
                String un = rs.getString(1);
                String fn = rs.getString(2);
                String ln = rs.getString(3);
                String em = rs.getString(4);
                DefaultTableModel tbml = (DefaultTableModel) tbl_ud.getModel();
                String[] tbData = {un,fn,ln,em};
                tbml.addRow(tbData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(User_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void calculateUser(Connection con){
        try {
            String q = "select count(*) from user_details";
            PreparedStatement ps = con.prepareStatement(q);
            ResultSet rs = ps.executeQuery(q);
            while(rs.next()){
                int cnt = rs.getInt(1);
                txt_totalusers.setText(String.valueOf(cnt));
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(User_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void TableHeader()
    {
        JTableHeader thead = tbl_ud.getTableHeader();
        thead.setBackground(Color.BLACK);
        thead.setFont(new Font("Times New Roman", Font.BOLD, 16));
        
        TableColumn col1 = tbl_ud.getColumnModel().getColumn(0);
        col1.setPreferredWidth(130);
        TableColumn col2 = tbl_ud.getColumnModel().getColumn(1);
        col2.setPreferredWidth(130);
        TableColumn col3 = tbl_ud.getColumnModel().getColumn(2);
        col3.setPreferredWidth(130);
        TableColumn col4 = tbl_ud.getColumnModel().getColumn(3);
        col4.setPreferredWidth(250);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_totalusers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ud = new javax.swing.JTable();
        btn_searchuser = new javax.swing.JButton();
        userdetails_back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/UserDetail_Img.png"))); // NOI18N
        jLabel1.setText(" User Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, 934, 55));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("* Total Users :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 148, -1, -1));

        txt_totalusers.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt_totalusers.setForeground(new java.awt.Color(255, 0, 0));
        txt_totalusers.setText("0");
        getContentPane().add(txt_totalusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 148, 37, -1));

        tbl_ud.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tbl_ud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "First Name", "Last Name", "E-Mail Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ud.setRowHeight(25);
        tbl_ud.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_ud);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 190, 861, 259));

        btn_searchuser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_searchuser.setText("Search User");
        btn_searchuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchuserActionPerformed(evt);
            }
        });
        getContentPane().add(btn_searchuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 489, 120, -1));

        userdetails_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userdetails_back.setText("Back");
        userdetails_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userdetails_backActionPerformed(evt);
            }
        });
        getContentPane().add(userdetails_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 489, 102, -1));

        jPanel1.setBackground(new java.awt.Color(238, 78, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 936, 100));

        jPanel2.setBackground(new java.awt.Color(252, 237, 218));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 936, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchuserActionPerformed
        // TODO add your handling code here:
        dispose();
        Search_User su = new Search_User();
    }//GEN-LAST:event_btn_searchuserActionPerformed

    private void userdetails_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userdetails_backActionPerformed
        // TODO add your handling code here:
        dispose();
        Admin_Dashboard ad = new Admin_Dashboard();
    }//GEN-LAST:event_userdetails_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_searchuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ud;
    private javax.swing.JLabel txt_totalusers;
    private javax.swing.JButton userdetails_back;
    // End of variables declaration//GEN-END:variables
}
